/**
 * Product Generator
 * Scaffolds `products/{name}/{api,web}` by composing the existing api and
 * webapp generators, then writes a `product.config.ts` declaration (modules,
 * plans, roles) validated against the shipped Product/Module/Plan/ProductRole
 * schema.
 * @core/cli
 */

import path from 'node:path';

import fsExtra from 'fs-extra';
import ora from 'ora';

const fs = fsExtra;

import type { GeneratorResult } from '../types.js';
import { directoryExists, ensureDir, getProductsDir } from '../utils/index.js';

import { generateApi } from './api.generator.js';
import {
  createDefaultProductDeclaration,
  validateProductDeclaration,
  type ProductDeclaration,
} from './product-declaration.js';
import { generateWebapp } from './webapp.generator.js';

/** Options for scaffolding a new product bundle */
export interface ProductGeneratorOptions {
  /** Product name (kebab-case) */
  name: string;
  /** Target directory (defaults to products/{name}) */
  targetDir?: string | undefined;
  /** API URL the scaffolded webapp should point at */
  apiUrl?: string | undefined;
  /** Initial theme for the scaffolded webapp */
  theme?: string | undefined;
}

/**
 * Generate a new product bundle: `api/`, `web/`, and `product.config.ts`.
 */
export async function generateProduct(options: ProductGeneratorOptions): Promise<GeneratorResult> {
  const spinner = ora('Scaffolding product...').start();
  const warnings: string[] = [];
  const createdFiles: string[] = [];

  const targetDir = options.targetDir ?? path.join(getProductsDir(), options.name);

  if (await directoryExists(targetDir)) {
    spinner.fail(`Directory already exists: ${targetDir}`);
    return {
      success: false,
      appPath: targetDir,
      message: `Directory already exists: ${targetDir}`,
      createdFiles: [],
      warnings: [],
    };
  }

  const declaration = createDefaultProductDeclaration(options.name);
  const validation = validateProductDeclaration(declaration);
  if (!validation.valid) {
    spinner.fail('Invalid product declaration');
    return {
      success: false,
      appPath: targetDir,
      message: `Invalid product declaration: ${validation.errors.join('; ')}`,
      createdFiles: [],
      warnings: [],
    };
  }

  spinner.text = 'Generating api/...';
  const apiResult = await generateApi({
    name: options.name,
    targetDir: path.join(targetDir, 'api'),
    database: true,
    auth: true,
  });
  if (!apiResult.success) {
    spinner.fail(apiResult.message);
    return { ...apiResult, appPath: targetDir };
  }
  createdFiles.push(...apiResult.createdFiles);
  warnings.push(...apiResult.warnings);

  spinner.text = 'Generating web/...';
  const webResult = await generateWebapp({
    name: options.name,
    targetDir: path.join(targetDir, 'web'),
    apiUrl: options.apiUrl,
    theme: options.theme,
  });
  if (!webResult.success) {
    spinner.fail(webResult.message);
    return { ...webResult, appPath: targetDir };
  }
  createdFiles.push(...webResult.createdFiles);
  warnings.push(...webResult.warnings);

  spinner.text = 'Writing product.config.ts...';
  await ensureDir(targetDir);
  const configPath = path.join(targetDir, 'product.config.ts');
  await fs.writeFile(configPath, renderProductConfig(declaration), 'utf-8');
  createdFiles.push(configPath);

  spinner.succeed(`Product "${options.name}" scaffolded at ${targetDir}`);

  return {
    success: true,
    appPath: targetDir,
    message: `Product "${options.name}" scaffolded successfully`,
    createdFiles,
    warnings,
  };
}

/**
 * Render the `product.config.ts` declaration file: the captured declaration
 * plus a `seedProduct` helper any Prisma-connected caller (e.g. an api-iam
 * seed script) can call to upsert the Product/Module/Plan/PlanModule/
 * ProductRole rows. `packages/cli` never connects to a database itself —
 * `ProductSeedClient` is a minimal structural interface, not `@prisma/client`.
 */
function renderProductConfig(declaration: ProductDeclaration): string {
  return `/**
 * ${declaration.name} — Product Declaration
 * Generated by \`core new product\`
 *
 * Declares this product's Product/Module/Plan/ProductRole rows. Edit the
 * values below, then call \`seedProduct\` from a Prisma-connected context
 * (e.g. an api-iam seed script) to persist them.
 */

/** Minimal structural subset of a Prisma client this file needs to seed rows */
export interface ProductSeedClient {
  product: { upsert: (args: unknown) => Promise<unknown> };
  module: { upsert: (args: unknown) => Promise<unknown> };
  plan: { upsert: (args: unknown) => Promise<unknown> };
  planModule: { upsert: (args: unknown) => Promise<unknown> };
  productRole: { upsert: (args: unknown) => Promise<unknown> };
}

export const productDeclaration = ${JSON.stringify(declaration, null, 2)} as const;

export async function seedProduct(prisma: ProductSeedClient): Promise<void> {
  await prisma.product.upsert({
    where: { id: productDeclaration.id },
    create: {
      id: productDeclaration.id,
      name: productDeclaration.name,
      description: productDeclaration.description,
    },
    update: { name: productDeclaration.name, description: productDeclaration.description },
  });

  for (const module of productDeclaration.modules) {
    await prisma.module.upsert({
      where: { id: module.id },
      create: { ...module, productId: productDeclaration.id },
      update: { ...module, productId: productDeclaration.id },
    });
  }

  for (const plan of productDeclaration.plans) {
    const { moduleIds, ...planFields } = plan;
    await prisma.plan.upsert({
      where: { id: plan.id },
      create: { ...planFields, productId: productDeclaration.id },
      update: { ...planFields, productId: productDeclaration.id },
    });

    for (const moduleId of moduleIds) {
      await prisma.planModule.upsert({
        where: { planId_moduleId: { planId: plan.id, moduleId } },
        create: { planId: plan.id, moduleId },
        update: {},
      });
    }
  }

  for (const role of productDeclaration.roles) {
    await prisma.productRole.upsert({
      where: { productId_key: { productId: productDeclaration.id, key: role.key } },
      create: { productId: productDeclaration.id, key: role.key, name: role.name },
      update: { name: role.name },
    });
  }
}
`;
}
