import { randomUUID } from 'crypto'
import type { DocumentRepository, PaymentRepository } from '../repositories/index.js'
import type { StorageAdapter } from '../adapters/index.js'
import { toContractPayment, toInvoiceListItem } from '../lib/payment-mapper.js'
import { ConflictError, ForbiddenError, NotFoundError } from '../errors.js'

export type BillingServiceDeps = {
  documentRepo: DocumentRepository
  storageAdapter: StorageAdapter
  paymentRepo: PaymentRepository
}

/**
 * The tenant's invoice PDF, if settlement has produced it.
 *
 * submit.service creates the row as a `pending` placeholder with a storageKey
 * of 'pending' — you don't invoice what hasn't been paid — so a row existing is
 * not the same as a file existing.
 */
function readyInvoiceDocumentId(
  documents: { id: string; type: string; status: string }[],
): string | null {
  return documents.find((doc) => doc.type === 'invoice' && doc.status === 'ready')?.id ?? null
}

export function createBillingService(deps: BillingServiceDeps) {
  const { documentRepo, storageAdapter, paymentRepo } = deps

  async function getSignedDocumentUrl(params: {
    documentId: string
    tenantUuid: string
  }): Promise<{ url: string; expiresAt: Date }> {
    const { documentId, tenantUuid } = params

    const document = await documentRepo.findById(documentId)

    if (!document) {
      throw new NotFoundError('billing.document_not_found')
    }

    if (document.tenantId !== tenantUuid) {
      throw new ForbiddenError('auth.forbidden')
    }

    // Invoices are placeholder rows (status: 'pending') until settlement generates
    // the real PDF — see submit.service.ts / settlement.service.ts.
    if (document.status !== 'ready') {
      throw new ConflictError('billing.document_not_ready', `Document ${documentId} is not ready yet`)
    }

    const url = await storageAdapter.signedUrl({ key: document.storageKey, ttlSeconds: 300 })

    return {
      url,
      expiresAt: new Date(Date.now() + 300_000),
    }
  }

  async function getPaymentMethod(): Promise<{ paymentMethod: null }> {
    return { paymentMethod: null }
  }

  async function requestPaymentMethodChange(): Promise<{ id: string }> {
    return { id: randomUUID() }
  }

  /**
   * The tenant's invoice history.
   *
   * There is no invoicing subsystem: nothing issues a document on a billing
   * cycle, and no row anywhere carries an invoice number or a due date. What
   * does exist is the payment — the charge — and one invoice PDF per tenant,
   * generated by settlement.service on first activation.
   *
   * So an invoice here is that charge seen fiscally: what was billed, when, and
   * whether it was settled, with the PDF attached once it exists. That is a
   * projection, not an invented record, and it is why the list overlaps with
   * /billing/payments — the payment log is the same events seen operationally
   * (method, reference, who settled it and why).
   */
  async function listInvoices(params: {
    tenantUuid: string
    page: number
    pageSize: number
  }): Promise<{
    items: ReturnType<typeof toInvoiceListItem>[]
    total: number
    page: number
    pageSize: number
  }> {
    const { tenantUuid, page, pageSize } = params
    const [payments, documents] = await Promise.all([
      paymentRepo.listByTenant(tenantUuid),
      documentRepo.findByTenantId(tenantUuid),
    ])

    const documentId = readyInvoiceDocumentId(documents)
    const start = (page - 1) * pageSize

    return {
      items: payments
        .slice(start, start + pageSize)
        // A payment that never settled has no document to offer, whether or not
        // the tenant has one from some other charge.
        .map((payment) =>
          toInvoiceListItem(payment, payment.status === 'approved' ? documentId : null),
        ),
      total: payments.length,
      page,
      pageSize,
    }
  }

  /**
   * The download behind an invoice row. `invoiceId` is a payment id: the row it
   * came from is a projection of that payment, so this resolves the tenant's
   * invoice document and hands back the same signed URL the document endpoint
   * would.
   */
  async function getInvoiceSignedUrl(params: {
    invoiceId: string
    tenantUuid: string
  }): Promise<{ url: string; expiresAt: Date }> {
    const { invoiceId, tenantUuid } = params

    const payments = await paymentRepo.listByTenant(tenantUuid)
    // Scoped to the tenant's own payments, so an id from another tenant is
    // simply absent — 404, never a 403 confirming it exists elsewhere.
    const payment = payments.find((candidate) => candidate.id === invoiceId)
    if (!payment) {
      throw new NotFoundError('billing.invoice_not_found', `Invoice ${invoiceId} not found`)
    }

    const documents = await documentRepo.findByTenantId(tenantUuid)
    const documentId = readyInvoiceDocumentId(documents)
    if (payment.status !== 'approved' || documentId === null) {
      throw new NotFoundError(
        'billing.invoice_document_not_found',
        `Invoice ${invoiceId} has no document yet`,
      )
    }

    return getSignedDocumentUrl({ documentId, tenantUuid })
  }

  // ponytail: paginates in-memory over listByTenant — this list is scoped to
  // one tenant's payments (small, not a system-wide table scan) and adding a
  // DB-paginated repo method isn't justified yet. Revisit if a tenant
  // accumulates hundreds of payments.
  async function listPayments(params: {
    tenantUuid: string
    page: number
    pageSize: number
  }): Promise<{ items: ReturnType<typeof toContractPayment>[]; total: number; page: number; pageSize: number }> {
    const { tenantUuid, page, pageSize } = params
    const all = await paymentRepo.listByTenant(tenantUuid)
    const start = (page - 1) * pageSize
    return {
      items: all.slice(start, start + pageSize).map((p) => toContractPayment(p)),
      total: all.length,
      page,
      pageSize,
    }
  }

  return {
    getSignedDocumentUrl,
    getPaymentMethod,
    requestPaymentMethodChange,
    listInvoices,
    getInvoiceSignedUrl,
    listPayments,
  }
}

export type BillingService = ReturnType<typeof createBillingService>
