/**
 * Markdown Generator Orchestrator
 * Generates API documentation from parsed OpenAPI spec
 * @core/cli
 */

import path from 'node:path';

import fsExtra from 'fs-extra';

import type {
  ParsedOpenApi,
  DocsSyncOptions,
  DocsSyncResult,
  OpenApiEndpoint,
} from '../../types.js';

import { groupEndpointsByTag } from './openapi-parser.js';
import { generateApiIndexMarkdown, tagToSlug } from './templates/api-index.js';
import { generateResourceMarkdown } from './templates/api-resource.js';

const fs = fsExtra;

// ============================================================================
// Constants
// ============================================================================

/** Default output directory relative to monorepo root */
const DEFAULT_OUTPUT_DIR = 'apps/docs/src/content/generated/api';

/** Generated file header comment - inserted after frontmatter */
const GENERATED_HEADER = `
<!-- 
  THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
  Generated by @core/cli docs:sync command.
  Re-run the command to update this documentation.
-->
`;

/**
 * Insert generated header after frontmatter.
 * Frontmatter must start at line 1 for gray-matter to parse it.
 */
function insertHeaderAfterFrontmatter(content: string): string {
  // Find the closing --- of frontmatter
  const frontmatterRegex = /^(---\n[\s\S]*?\n---\n)/;
  const match = frontmatterRegex.exec(content);
  if (match?.[1]) {
    const frontmatter = match[1];
    const body = content.slice(frontmatter.length);
    return frontmatter + GENERATED_HEADER + body;
  }
  // No frontmatter found, prepend header
  return GENERATED_HEADER + content;
}

// ============================================================================
// Types
// ============================================================================

/** Result of generating a single file */
interface GeneratedFile {
  /** Relative path from output directory */
  relativePath: string;
  /** Absolute path on disk */
  absolutePath: string;
  /** File content */
  content: string;
  /** Whether this is the index file */
  isIndex: boolean;
}

/** Generator context */
interface GeneratorContext {
  /** Parsed OpenAPI specification */
  spec: ParsedOpenApi;
  /** Grouped endpoints by tag */
  groups: Map<string, OpenApiEndpoint[]>;
  /** Output directory (absolute path) */
  outputDir: string;
  /** Whether to include examples in docs */
  includeExamples: boolean;
  /** API name for category grouping */
  apiName: string;
}

// ============================================================================
// File Generation
// ============================================================================

/**
 * Generate the index file
 */
function generateIndexFile(ctx: GeneratorContext): GeneratedFile {
  const content = generateApiIndexMarkdown(ctx.spec, ctx.groups, {
    order: 1,
    apiName: ctx.apiName,
  });

  return {
    relativePath: 'index.md',
    absolutePath: path.join(ctx.outputDir, 'index.md'),
    content: insertHeaderAfterFrontmatter(content),
    isIndex: true,
  };
}

/**
 * Generate resource files for each tag
 */
function generateResourceFiles(ctx: GeneratorContext): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  let order = 10;

  for (const [tag, endpoints] of ctx.groups) {
    const slug = tagToSlug(tag);
    const relativePath = `${slug}.md`;

    const content = generateResourceMarkdown(tag, endpoints, {
      order,
      includeExamples: ctx.includeExamples,
      apiName: ctx.apiName,
    });

    files.push({
      relativePath,
      absolutePath: path.join(ctx.outputDir, relativePath),
      content: insertHeaderAfterFrontmatter(content),
      isIndex: false,
    });

    order += 10;
  }

  return files;
}

/**
 * Generate all markdown files
 */
function generateAllFiles(ctx: GeneratorContext): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Index file
  files.push(generateIndexFile(ctx));

  // Resource files
  files.push(...generateResourceFiles(ctx));

  return files;
}

// ============================================================================
// File Writing
// ============================================================================

/**
 * Ensure output directory exists
 */
async function ensureOutputDir(outputDir: string): Promise<void> {
  await fs.ensureDir(outputDir);
}

/**
 * Write a single file to disk
 */
async function writeFile(file: GeneratedFile): Promise<void> {
  await fs.writeFile(file.absolutePath, file.content, 'utf-8');
}

/**
 * Write all files to disk
 */
async function writeAllFiles(files: GeneratedFile[]): Promise<void> {
  await Promise.all(files.map(writeFile));
}

// ============================================================================
// Dry Run Mode
// ============================================================================

/**
 * Log files that would be generated (dry run mode)
 */
function logDryRun(files: GeneratedFile[], verbose: boolean): void {
  console.log('\n[Dry Run] Would generate the following files:\n');

  for (const file of files) {
    console.log(`  - ${file.relativePath}`);

    if (verbose) {
      console.log(`    Path: ${file.absolutePath}`);
      console.log(`    Size: ${String(file.content.length)} bytes`);
      console.log('');
    }
  }

  console.log(`\nTotal: ${String(files.length)} files\n`);
}

// ============================================================================
// Check Mode
// ============================================================================

/**
 * Compare generated content with existing files
 * Returns diff information if files differ
 */
async function checkExistingFiles(
  files: GeneratedFile[]
): Promise<{ upToDate: boolean; diff: string[] }> {
  const diff: string[] = [];

  for (const file of files) {
    const exists = await fs.pathExists(file.absolutePath);

    if (!exists) {
      diff.push(`+ ${file.relativePath} (new file)`);
      continue;
    }

    const existingContent = await fs.readFile(file.absolutePath, 'utf-8');

    if (existingContent !== file.content) {
      diff.push(`~ ${file.relativePath} (modified)`);
    }
  }

  return {
    upToDate: diff.length === 0,
    diff,
  };
}

// ============================================================================
// Main Generator
// ============================================================================

/**
 * Resolve output directory to absolute path
 */
function resolveOutputDir(outputDir: string | undefined, workingDir: string): string {
  if (outputDir) {
    if (path.isAbsolute(outputDir)) {
      return outputDir;
    }
    return path.resolve(workingDir, outputDir);
  }

  // Default: look for monorepo root
  return path.resolve(workingDir, DEFAULT_OUTPUT_DIR);
}

/**
 * Generate API documentation from parsed OpenAPI spec
 *
 * @param spec - Parsed OpenAPI specification
 * @param options - Generation options
 * @returns Result with list of generated files
 */
export async function generateApiDocs(
  spec: ParsedOpenApi,
  options: DocsSyncOptions = {}
): Promise<DocsSyncResult> {
  const workingDir = process.cwd();
  const outputDir = resolveOutputDir(options.outputDir, workingDir);
  const verbose = options.verbose ?? false;
  const dryRun = options.dryRun ?? false;
  const check = options.check ?? false;

  // Group endpoints by tag
  const groups = groupEndpointsByTag(spec.endpoints);

  if (groups.size === 0) {
    return {
      success: false,
      message: 'No endpoints found in OpenAPI specification',
      files: [],
    };
  }

  // Create generator context
  const ctx: GeneratorContext = {
    spec,
    groups,
    outputDir,
    includeExamples: true,
    apiName: options.name ?? 'api',
  };

  // Generate all files in memory
  const files = generateAllFiles(ctx);

  // Check mode: compare with existing files
  if (check) {
    const { upToDate, diff } = await checkExistingFiles(files);

    return {
      success: true,
      message: upToDate ? 'Documentation is up to date' : 'Documentation is out of date',
      files: files.map((f) => f.relativePath),
      upToDate,
      diff,
    };
  }

  // Dry run mode: just log what would happen
  if (dryRun) {
    logDryRun(files, verbose);

    return {
      success: true,
      message: `Would generate ${String(files.length)} files (dry run)`,
      files: files.map((f) => f.relativePath),
    };
  }

  // Actual generation: write files to disk
  try {
    await ensureOutputDir(outputDir);
    await writeAllFiles(files);

    if (verbose) {
      console.log('\nGenerated files:');
      for (const file of files) {
        console.log(`  - ${file.relativePath}`);
      }
      console.log(`\nOutput directory: ${outputDir}`);
    }

    return {
      success: true,
      message: `Generated ${String(files.length)} API documentation files`,
      files: files.map((f) => f.relativePath),
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';

    return {
      success: false,
      message: `Failed to generate documentation: ${errorMessage}`,
      files: [],
    };
  }
}

/**
 * Generate API docs from source (URL or file path)
 * Convenience function that combines loading and generating
 */
export async function generateApiDocsFromSource(
  source: string,
  options: DocsSyncOptions = {}
): Promise<DocsSyncResult> {
  // Import here to avoid circular dependency
  const { loadOpenApiSpec } = await import('./openapi-parser.js');

  try {
    const spec = await loadOpenApiSpec(source);
    return await generateApiDocs(spec, options);
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';

    return {
      success: false,
      message: `Failed to load OpenAPI spec: ${errorMessage}`,
      files: [],
    };
  }
}
